### PR TITLE
Suggest more customization using site variables [WIP]

### LINKED ISSUE #94: Make Working on a cluster more universal

### PR DESCRIPTION
**Pull request by Sabryr**
Suggest more customization after using the material with other cluster with differing setups. 

1. include site.ls_user_home_output, so different ls out puts can be showing for different cluster setups Fixes #94

### CODE REVIEW

**Comment by Sabryr** [comment]
I noticed https://github.com/hpc-carpentry/hpc-intro/pull/101 is not merged yet. So this PR on hold until  after it is merged, as this may be implemented differently if snippet are used.

**Comment by psteinb** [comment]
@Sabryr could you please see to fixing the conflicts? That would be great.

**Comment by Sabryr** [comment]
Sorry for the late response, was not following this. I will update with conflict fixes ASAP

**Comment by psteinb** [comment]
I have to apologize for not reviewing your PR earlier. Take your time and remove the WIP once done.

**Comment by tkphd** [comment]
Late to the party on this one, but I'm not in favor of merging this, even if it's rebased.
Contents of the home directory will vary so widely from site-to-site and user-to-user, a site variable can't do it justice.
The minimal solution, in my opinion, is to create a discussion box to have the instructor and learners run `ls` together and discuss the output in realtime. One step above would be to include a "solution" snippet, showing the default contents of a user's home directory. Sometimes this is empty, so `ls -a` would be appropriate; often it includes some skeleton files, and symlinks to scratch, work, etc.

**Comment by psteinb** [comment]
:facepalm: that is a good point I oversaw. I support the suggestion by @tkphd. How does that sound to you @Sabryr ?

**Comment by tkphd** [comment]
Superseded by #169.

**Pull request closed without merging**
