### PR TITLE
[WIP] Make scheduler a variable

### PR DESCRIPTION
**Pull request by psteinb**
I am  starting to gradually replace all code snippets that use slurm by including a snippet. I'll remove the WIP tag once I am done. 
Feel free to comment/review at this point already if you want.

### CODE REVIEW

**Comment by tkphd** [comment]
Slurm seems to be the dominant scheduler for HPC these days. What alternative/legacy/up-and-coming schedulers do we (you) plan to support? PBS/Torque? Grid Engine? Moab? OpenLava? 

As an alternative, are there specific platforms we intend to develop lessons for, *e.g.*, Archer, Stampede, or a user-defined template, for which the scheduler is one of a number of specializations?
(Not recommending this approach, it's a [straw man](https://en.m.wikipedia.org/wiki/Straw_man) ) 

I'm still wrapping my head around the structure of things.

**Comment by ChristinaLK** [comment]
+1 to most of your comments @psteinb (sorry I didn't see this earlier!  I've been checking!)
I also would split scheduler lesson into at least two parts -- in a previous draft of stuff I've written (https://christinalk.github.io/chtc-htc/) I had:
- what is a job? 
- submitting a job (submit file + submit command)
- life cycle of a job (monitoring, removing, etc.)

For cores/memory/cluster schematic -- maybe add them here: https://hpc-carpentry.github.io/hpc-intro/11-cluster/index.html?

**Comment by ChristinaLK** [comment]
Also see @pdoehle #39

**Comment by psteinb** [comment]
I condensed comments from here and #39 into #40. I'll close this PR unmerged in order to focus on pieces of work in a more granular way and to have the consent of the community first.

**Pull request closed without merging**
