### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by mikerenfro**
Looks like we missed a path in the .travis.yml to match the renamed Norway folder.

### CODE REVIEW

**Comment by tkphd** [comment]
Looks good, except [Norway_SIGMA2_SAGA_slurm/_config_options.yml](https://github.com/hpc-carpentry/hpc-intro/blob/update-travis-sigma2-saga/_includes/snippets_library/Norway_SIGMA2_SAGA_slurm/_config_options.yml) has the wrong path.

**Comment by mikerenfro** [comment]
These changes are getting a bit deeper than I'm comfortable with on my own. Travis is failing on trying to include `queue-info.snip`, which used to be `info.snip`.

So I think we're going to need some more changes along the lines of #178 to match the new filenames. Pinging @Sabryr to confirm, and then y'all can decide if I should cancel this PR and wait for another one where the Norway site builds completely.

**Comment by tkphd** [comment]
Oh, I see: since #163 was merged, the Norway snippet files need to be renamed.

**Comment by Sabryr** [comment]
Oh, I see the issue is on my side due to refracting. I see something going on in https://github.com/hpc-carpentry/hpc-intro/pull/188 as well. Not sure whats the next step is

**Comment by reid-a** [comment]
It looks like #188 fixes two path issues, including the rename of the Norway paths, clearing the way for this one. 

The next step once that one is merged and passes CI is to review/merge this one, then #186 can proceed (once suitably rebased.)

This assumes 188 on its own passes CI.

**Comment by tkphd** [comment]
The build is passing, despite what Travis says.

**Comment by psteinb** [comment]
The build for this appears to fail:
```
Configuration file: _config.yml

            Source: /home/travis/build/hpc-carpentry/hpc-intro

       Destination: /home/travis/build/hpc-carpentry/hpc-intro/_site

 Incremental build: disabled. Enable with --incremental

      Generating... 

      Remote Theme: Using theme carpentries/carpentries-theme

  Liquid Exception: Could not locate the included file 'base_path.html' in any of ["/home/travis/build/hpc-carpentry/hpc-intro/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /home/travis/build/hpc-carpentry/hpc-intro/_episodes/11-hpc-intro.md

jekyll 3.8.7 | Error:  Could not locate the included file 'base_path.html' in any of ["/home/travis/build/hpc-carpentry/hpc-intro/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.

Makefile:53: recipe for target 'site' failed

make: *** [site] Error 1

The command "make --always-make site" exited with 2.
```
@tkphd can you help?

**Comment by tkphd** [comment]
@psteinb was this a local build, or the "continuous-integration/travis-ci/push" test error? I can't restart that Travis build, but all the others passed testing, and building it locally appears to work.

**Comment by psteinb** [comment]
indeed I was referring to the `continuous-integration/travis-ci/push` test failing.

**Comment by tkphd** [comment]
OK. I've made a trivial commit to restart the builds -- hopefully, they will unequivocally pass this time.

**Pull request merged**
