### PR TITLE
Add spellchecker to ci

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
@psteinb Looks like travis is currently not configured to run for PRs.

The purpose of this PR is to catch (easy) spelling mistakes in PRs.

**Comment by ocaisa** [comment]
When travis can run I will minimise the changes here

**Comment by ocaisa** [comment]
I configured travis on my own fork so checked that this branch is actually passing, see https://github.com/ocaisa/hpc-intro/pull/1

A maintainer needs to configure travis to pick up PRs for CI

**Comment by psteinb** [comment]
I am looking into it. I just saw that the travis badge is pointing to @tkphd and not this repo. Not sure why.
@tkphd could you comment on that?

**Comment by psteinb** [comment]
@ocaisa why is `before_install` slow?

**Comment by psteinb** [comment]
just checked, hpccarpentry is not visibile as a project organisation for my travisCI account. I'll try to figure this one out. Maybe we can then also fix the issue of the tests running running for @tkphd

**Comment by ocaisa** [comment]
> @ocaisa why is `before_install` slow?

The ruby stuff takes some time to install but for the spellchecking it's not necessary

**Comment by tkphd** [comment]
@psteinb, looks like I configured it for my branch as a test, and never switched over, in part because I did not have the authority at the time. Changing the badge URL shouldn't be a problem. Are you visiting [travis-ci.org](https://travis-ci.org/hpc-carpentry) (instead of -.com)?

**Comment by psteinb** [comment]
alright, someone that owns the hpccarpentry organization had to approve my request to allow travis CI to interact with all repos. I've now added hpc-intro to [travis CI](https://travis-ci.com). I'll submit a PR to change the badge URL.

**Comment by psteinb** [comment]
I'll merge this now to move along with the change of the landing page.

**Pull request merged**
